// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7VzjOkXWAW4nqMD2ueE3DcN_kJLBQvLw',
    appId: '1:670967152439:web:09e5e6e46be57a20a0e4b2',
    messagingSenderId: '670967152439',
    projectId: 'gfor2-e681d',
    authDomain: 'gfor2-e681d.firebaseapp.com',
    storageBucket: 'gfor2-e681d.firebasestorage.app',
    measurementId: 'G-SZHBVYZ3NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYObdjot2341BtJh_273ItHl8TZvaFmGs',
    appId: '1:670967152439:android:7ed8826919221b96a0e4b2',
    messagingSenderId: '670967152439',
    projectId: 'gfor2-e681d',
    storageBucket: 'gfor2-e681d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBKKacMGM1neeui8vRksbVlsA5kfjQcTE',
    appId: '1:670967152439:ios:d2c9d6889327560aa0e4b2',
    messagingSenderId: '670967152439',
    projectId: 'gfor2-e681d',
    storageBucket: 'gfor2-e681d.firebasestorage.app',
    iosBundleId: 'com.malgnst.g42',
  );
}
